# made with reference: https://github.com/hack4impact-uiuc/globalgiving-tool/blob/master/.circleci/config.yml

version: 2
jobs:
  # microservice_test:
  #   docker:
  #     - image: circleci/python:3.7.0-browsers
  #   steps:
  #     - checkout
  #     - run:
  #         command: |
  #           cd microservices
  #           pip install -r requirements.txt --user
  #           pip install -r requirements-dev.txt --user
  #           /home/circleci/.local/bin/pytest
  lint:
    docker:
      - image: circleci/python:3.7.0-browsers
    steps:
      - checkout
      - run:
          command: |
            cd src
            pip install -r requirements.txt --user
            pip install -r requirements-dev.txt --user
            /home/circleci/.local/bin/black . --check
workflows:
  version: 2
  build-test:
    jobs:
      # - test
      - lint
